### ISSUE TITLE
when train_cifar.py is running, there is some error.

### ISSUE THREAD

**Issue by MachineCF** [eric8607242/SGNAS#4]
Error:
Traceback (most recent call last):
  File "/home/lcf/project/SGNAS/train_cifar.py", line 97, in <module>
    arch_param = generator(prior, normalize_hardware_constraint, noise)
  File "/home/lcf/anaconda3/envs/DALLE/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given

Code:

arch_param = generator(prior, normalize_hardware_constraint, noise)
 `
def forward(self, x, hc):
        y = x.view(1, 1, *x.shape)
..........
        return y
`
TypeError: forward() takes 3 positional arguments but 4 were given

**Comment by sungwool** [comment]
Hello, I'm one of the users.

I faced the same problem as you. 
However, the problem can be solved easily. 
If the last argument, noise, is removed, the code will work normally.

For example, 
[before]
arch_param = generator(prior, normalize_hardware_constraint, noise)

[after]
arch_param = generator(prior, normalize_hardware_constraint)

I hope you have a good day. 😊

**Comment by yiyi9527** [comment]
thank god，it takes me a lot of time

**Comment by eric8607242** [comment]
Sorry for the late reply, and thanks for the Sungwool's response.

If there is any question, please feel free to let me know. Thank you.

I have pushed a new version to fix this error. Sorry again
